### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by neox95** [Zuxelus/Energy-Control#1]
Hey there,
I think nuclear control was under original copyright from shedar, with restrictive open-source license (with copyright citation needed).
You should provide the same license file than nuclear control 2, isn't it? 

(sorry for this week of silence, bunch of work 😔)

**Comment by neox95** [comment]
Another problem is that no license file means all right reserved by default, so fork, clone, are prohibited.

**Comment by Zuxelus** [comment]
Updated
