### ISSUE TITLE
[BUG]Advanced Information Panel

### ISSUE THREAD

**Issue by Romz24** [Zuxelus/Energy-Control#10]
When I install more than 1 sensor, I can’t configure the 2 and 3 sensors, they simply don’t press the button. Also I can not set the header for 2 and 3 sensors, it simply refuses to persist.

![image](https://user-images.githubusercontent.com/2458113/86839572-443c5780-c0aa-11ea-94f2-59f0ba00b705.png)

**Comment by Zuxelus** [comment]
Should be fixed in [Info Panel bugs fix, AppEng support](https://github.com/Zuxelus/Energy-Control/commit/87f7e7cc2c4e1a3e01cdab914ff3bb6b3918c110) (version 1.12.2-0.1.4a)

**Comment by Romz24** [comment]
Checked, the problem is really resolved.
