### ISSUE TITLE
[BUG]Stack Sensor Kit 

### ISSUE THREAD

**Issue by Romz24** [Zuxelus/Energy-Control#11]
I crafted 2 different Sensor Kits (**Energy Sensor Kit** and **Remote Toggle Kit**), when I dropped the Energy Sensor Kit, I picked it up and it turned into a Remote Toggle Kit, after that I got 2 identical Sensor Kits.

**Comment by Zuxelus** [comment]
Should be fixed in [Issues 11-13](https://github.com/Zuxelus/Energy-Control/commit/3aefd4d4d791be12133a00a05f0cf7ea74385343#diff-5223922e2abc6ffdb0a343c77b8cb542) (version 1.12.2-0.1.4b)

**Comment by Romz24** [comment]
This issue has been resolved, thanks
