### ISSUE TITLE
[BUG]AFSU

### ISSUE THREAD

**Issue by Romz24** [Zuxelus/Energy-Control#12]
I noticed that there is no way to use the Energy Sensor Kit on the AFSU, it seems like a mistake.

It would also be nice to be able to make an AFSU charging panel that will quickly charge clad armor.

**Comment by Zuxelus** [comment]
Should be fixed in [Issues 11-13](https://github.com/Zuxelus/Energy-Control/commit/3aefd4d4d791be12133a00a05f0cf7ea74385343#diff-7bf81d15447f73a82e1ccda3dd568c96) (version 1.12.2-0.1.4b)

**Comment by Romz24** [comment]
Thanks, problem solved.
