### ISSUE TITLE
[BUG]Energy Array Card

### ISSUE THREAD

**Issue by Romz24** [Zuxelus/Energy-Control#13]
I have more than 6 MFSUs in my system, but unfortunately I can’t combine more than 6 sensors.

![image](https://user-images.githubusercontent.com/2458113/87074864-2bf24700-c228-11ea-9316-c5206a5793d1.png)
![image](https://user-images.githubusercontent.com/2458113/87074886-344a8200-c228-11ea-8b73-24a1af2e6b24.png)

**Comment by Zuxelus** [comment]
Changed total cards from 6 to 16 in [Issues 11-13](https://github.com/Zuxelus/Energy-Control/commit/3aefd4d4d791be12133a00a05f0cf7ea74385343#diff-6c6565898c7c45e66d6b17281705301b) (version 1.12.2-0.1.4b)

**Comment by Romz24** [comment]
Thanks, problem solved.
