### ISSUE TITLE
[1.12-Crash-Compat] issue with GregTech Experimental

### ISSUE THREAD

**Issue by gatoborrachon** [Zuxelus/Energy-Control#19]
There's a crash on startup when you use the newest version of Energy Control (0.1.9) and GregTech 1.0-28
https://pastebin.com/RDK5AhEG

Link to the same issue on GregTech Experimental's Github: https://github.com/Su5eD/GregTech-Experimental/issues/21

**Comment by Su5eD** [comment]
As explained in the linked issue, the problem is on my side.
This issue can be closed.

**Comment by gatoborrachon** [comment]
ok
