### ISSUE TITLE
Clicking on the seed pouch in the seed library gui crashes the game

### ISSUE THREAD

**Issue by Geird** [Zuxelus/Energy-Control#20]
![2021-03-03_11 21 19 - Copy](https://user-images.githubusercontent.com/23565524/109843552-2f07d080-7c19-11eb-856c-c3b6df9b5b7d.png)

To reproduce, hook the seed library up to lv power, then open the interface and click on the seed pouch. The other four buttons do not seem to have this issue. 
[crash-2021-03-02_22.04.51-client.txt](https://github.com/Zuxelus/Energy-Control/files/6077787/crash-2021-03-02_22.04.51-client.txt)
[modlist.txt](https://github.com/Zuxelus/Energy-Control/files/6077788/modlist.txt)

**Comment by Zuxelus** [comment]
Should be fixed in EnergyControl-1.12.2-0.1.11.jar
