### ISSUE TITLE
[Suggestion] CraftTweaker Support (1.12.2)

### ISSUE THREAD

**Issue by MasterEnderman** [Zuxelus/Energy-Control#46]
Just as mentioned in your Discord. It would be great, if you could add CraftTweaker support for the "Kit Assembler".

**Comment by Zuxelus** [comment]
Added in 1.12.2-0.2.8
mods.energycontrol.KitAssembler.addRecipe(<minecraft:dirt>, <minecraft:dirt> * 2, <minecraft:dirt> * 3, <minecraft:diamond_block>, 100);
mods.energycontrol.KitAssembler.removeRecipe(<minecraft:redstone> * 2, <minecraft:iron_ingot>, <minecraft:flint>);
