### ISSUE TITLE
[1.7.10] Crash by using Fluid Sensor Kit on Buildcraft stuff (Prevents map load!!)

### ISSUE THREAD

**Issue by Ayliroe** [Zuxelus/Energy-Control#55]
Steps to reproduce:
- Place a BC refinery/tank/etc
- Right-click with Liquid Sensor Kit
- Put kit in Industrial Information Panel
- Activate panel with redstone

Crash report:
[crash-2022-05-31_15.07.33-server.txt](https://github.com/Zuxelus/Energy-Control/files/8805375/crash-2022-05-31_15.07.33-server.txt)

Prevents from reloading the map every time when the Information Panel gets loaded into memory, potentially "corrupting" worlds!

Mods:
buildcraft-7.1.24
EnergyControl-1.7.10-0.3.3
industrialcraft-2-2.2.827-experimental

Cheers!

**Comment by Zuxelus** [comment]
Was fixed in 1.7.10-0.3.3a (commit c649876dd17d3ba009dcbaab40c6776150c20cca) 5 days ago.

**Comment by Ayliroe** [comment]
Ah sorry, didn't see it as it's not on CurseForge!
