### ISSUE TITLE
[1.7.10] Crash with HBM NTM JameH2's fork X5098

### ISSUE THREAD

**Issue by MrPhaot** [Zuxelus/Energy-Control#84]
Even though the original mod shouldn't have that problem anymore, I still expirience crashes with energy control.
Thank you in advance!

[crash-2024-09-28_16.28.14-client.txt](https://github.com/user-attachments/files/17174781/crash-2024-09-28_16.28.14-client.txt)
[fml-client-latest.log](https://github.com/user-attachments/files/17174782/fml-client-latest.log)

**Comment by Millymilo00** [comment]
Have you tried using the beta release of energy control in it's github releases?
[https://github.com/Zuxelus/Energy-Control/releases/tag/1.7.10-0.3.5e](https://github.com/Zuxelus/Energy-Control/releases/tag/1.7.10-0.3.5e)

**Comment by MrPhaot** [comment]
Thanks! I tried and it worked. I hope the build will be released and won't stay in beta.
